version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: dronedb
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  drone_service:
    build: .
    restart: on-failure
    ports:
      - 7575:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
       - SPRING_PROFILES_ACTIVE=docker