server:
  port: 7575
spring:
  datasource:
    username: demo
    password: demo
    url: jdbc:mysql://localhost:3306/dronedb
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
logging:
  file:
    path: .
    name: drone_app.log