spring:
  datasource:
    username: demo
    password: demo
    url: jdbc:mysql://mysqldb:3306/dronedb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    
logging:
  file:
    path: .
    name: drone_app.log